apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test-component-debv
  namespace: build-e2e-hacbs-asdt
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: test-app-ssqz
        appstudio.openshift.io/component: test-component-debv
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test-component-debv-
      labels:
        appstudio.openshift.io/application: test-app-ssqz
        appstudio.openshift.io/component: test-component-debv
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: build-e2e-hacbs-asdt
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-python-basic.git
      - name: output-image
        value: quay.io/mkovarik/test-images@sha256:b19d27157d2f1a573f6a8c51f4fbfd455b343151be28262141df41ba7fb46308-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      podTemplate:
        imagePullSecrets:
        - name: redhat-appstudio-registry-pull-secret
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
